### ISSUE TITLE
Tops of Forestry fences

### ISSUE THREAD

**Issue by Antithasys** [Soartex-Modded/Modded-1.10.x#26]
The tops of the Forestry mod fences are not given a pattern.  [Here ](http://puu.sh/t3eX5/35e75e646a.png)is a screenshot.

**Comment by UnPure** [comment]
Are you sure that this problem isnt a forestry problem?
Shouldnt it use the vanilla forestry textures if the sortex textures are missing instead of an error texture?

**Comment by artdude543** [comment]
Fences are broken for some mods. We are aware of this issue and it will be fixed in time.

**Comment by Shoeboxam** [comment]
I have pushed a fix for this to the vanilla development pack, which will be released soon.


The current version of Soartex edits the base fence model to expect an additional texture. When a mod inherits from this overwritten file, it has broken texture references, because these custom textures have not been added to mod support!

The fix was to reimplement the fence model chain in soartex such that it does not edit the vanilla model file. With the custom implementation, the old vanilla fence model still exists, so it loads correctly in a mod environment.
